### PR TITLE
Give control to lua script

### PR DESCRIPTION
**Pull request by RozeFound**
Makes lua script in charge of invoking the sh script, it can still work as before as well.

### But it has problems:
- Too simple name parsing. For now in only works if your file is named like "Black Clover S1E1", I don't want to bother with more complex detection, if anyone is interested, go ahead. There is an option to manually enter the data, by triggering "script-binding/manual"
- Doesn't work in flatpak, sh script fail to execute from flatpak environment, possibly because of permissions i dunno.

### CODE REVIEW

**Comment by synacktraa** [comment]
Does this approach have any advantage over previous implementation?

**Comment by RozeFound** [comment]
Well, this way the user don't have to do anything. If the script detects the title, season and episode number, it'll automatically invoke the sh script, load the chapters and skip them if enabled.
I'm not a lua programmer, never written a line of lua before, so it might be unstable and/or contain some bugs/flaws, but at least, it works.

**Comment by synacktraa** [comment]
> Well, this way the user don't have to do anything. If the script detects the title, season and episode number, it'll automatically invoke the sh script, load the chapters and skip them if enabled.
> 
> I'm not a lua programmer, never written a line of lua before, so it might be unstable and/or contain some bugs/flaws, but at least, it works.

It will be better if you release it as your own project, this script is mainly being used by ani-cli, I don't think they will prefer this.

**Comment by RozeFound** [comment]
Makes sense

**Comment by po5** [comment]
@RozeFound [mpv-auto-chapters](https://github.com/po5/mpv-auto-chapters) does exactly this, with much more reliable filename parsing and anime identification, all automatically.

**Comment by RozeFound** [comment]
> [mpv-auto-chapters](https://github.com/po5/mpv-auto-chapters) does exactly this, with much more reliable filename parsing and anime identification, all automatically.

Huh, thanks! That's what I was looking for, and as you can see even tried to implement myself. Didn't know someone already did it for me!

**Pull request closed without merging**
