### PR TITLE
Windows Fix

### PR DESCRIPTION
**Pull request by Woreec**
First Time doign a commit so, sorry if this sucks

-Added Skript path for windows
-Changed skip api from curl to wget, since curl doesnt seem to work on alteast my machine, 
 additionally split up api pull for op and ed since it didnt work together when using wget.

Second point might be my Windows specifically, havent tested in on other machines.

Obv makes wget an aditional Dependency for Windows.

### CODE REVIEW

**Comment by synacktraa** [comment]
Looks good to me. Will merge it soon after testing.

**Comment by synacktraa** [comment]
> First Time doign a commit so, sorry if this sucks
> 
> -Added Skript path for windows -Changed skip api from curl to wget, since curl doesnt seem to work on alteast my machine, additionally split up api pull for op and ed since it didnt work together when using wget.
> 
> Second point might be my Windows specifically, havent tested in on other machines.
> 
> Obv makes wget an aditional Dependency for Windows.

I was going through your PR...can you tell me what is `$OS` env here? Where does the script defines `$api_url` variable?

**Comment by Woreec** [comment]
$OS is a predefined Variable in bash under windows which is equal to the Windows System Variable "OS" 
I dont know why $api_url isnt defined, let me look over it again i think i messed something up with copy pasting
Sorry about that thought i tested it the way i put it in the PR.
Also gonna change $OS to use $OSTYPE instead since thats a better way of doing it

**Comment by synacktraa** [comment]
> $OS is a predefined Variable in bash under windows which is equal to the Windows System Variable "OS" I dont know why $api_url isnt defined, let me look over it again i think i messed something up with copy pasting Sorry about that thought i tested it the way i put it in the PR. Also gonna change $OS to use $OSTYPE instead since thats a better way of doing it

`$OSTYPE` is indeed useful here. But I just noticed something that lua script path is being passed explicitly through `--script` flag, I will just move the `skip.lua` file to `$HOME/.config/ani-skip`. 

What kind of error did you face with curl here? Can you show the error? Calling aniskip api twice is unnecessary, I'll see If there's a solution with curl.

**Comment by synacktraa** [comment]
There was no problem with curl to begin with. I'll made some updates, it will work in the new release(working on readme rn). And thanks for telling me $OSTYPE env

**Comment by synacktraa** [comment]
Here's the new release with no extra dependencies: https://github.com/synacktraa/ani-skip/releases/tag/1.0.0
Try it out let me know If you face any issues. Thankyou.

**Pull request closed without merging**
